# Generated by Django 4.1.3 on 2022-11-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expired_at',
            field=models.DateTimeField(),
        ),
    ]
